name: Bedrock to GeckoLib Model Converter

on:
  push:
    paths:
      - "model.geo.json"

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do projeto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar conversor
        run: node converter.js

      - name: Enviar modelo convertido
        uses: actions/upload-artifact@v4
        with:
          name: GeckoLib-Model
          path: output/
